toucheHaut: Z
toucheBas: X
toucheGauche: Q
toucheDroite: D
toucheHautGauche: A
toucheGaucheBas: W
toucheBasDroite: C
toucheDroiteHaut: E
toucheSelect: S

nbLignes: 10
nbColonnes: 10

nbMax: 3
scoreMax: 500
deplacementMax: 10
