toucheHaut: z
toucheBas: x
toucheGauche: q
toucheDroite: d
toucheHautGauche: a
toucheGaucheBas: w
toucheBasDroite: c
toucheDroiteHaut: e
toucheSelect: s

nbNiveaux: 16

nbColonnesV: {10, 8, 10, 8, 9, 7, 9, 7, 6, 5, 6, 6, 4, 3, 4, 3}
nbLignesV: {10, 10, 8, 8, 9, 9, 7, 7, 6, 6, 5, 5, 4, 4, 3, 3}

nbMaxV: {6, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6}
scoreMaxV: {150, 200, 200, 250, 250, 300, 300, 350, 350, 400, 400, 450, 450, 500, 500, 550, 550, 600}
deplacementMaxV: {15, 14, 12, 13, 11, 10, 8, 9, 7, 7, 6, 6, 6, 5, 5, 4}
